version: '3.8'  

services:       

  zookeeper:    #
    image: confluentinc/cp-zookeeper:latest  
    environment:                             
      ZOOKEEPER_CLIENT_PORT: 2181           
      ZOOKEEPER_TICK_TIME: 2000             
    ports:
      - "2181:2181"                         

  kafka:         
    image: confluentinc/cp-kafka:latest    
    depends_on:  
      - zookeeper
    environment: 
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092  
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"                        

  postgres:      
    image: postgres:15                    
    environment:                         
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"                      

  user-service:  
    build:
      context: ./SpringTask\demo\spring           
      dockerfile: Dockerfile
    ports:
      - "8081:8081"                   
    environment:                         
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - kafka
      - postgres

  gateway:       
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    environment:
      SPRING_CLOUD_GATEWAY_ROUTES_0_URI: http://user-service:8081
    depends_on:
      - user-service

  notification-service:  
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - kafka
